# Generated by Django 5.2 on 2025-04-15 08:58

import AltinGiltApp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Elon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=200)),
                ('joylashuvi', models.CharField(max_length=100)),
                ('turi', models.CharField(choices=[('Uy', 'Uy'), ('Kvartira', 'Kvartira'), ('Yer', 'Yer')], default='Uy', max_length=10)),
                ('narxi', models.PositiveIntegerField()),
                ('batafsil', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elonlar', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=AltinGiltApp.models.elon_rasm_path)),
                ('elon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlar', to='AltinGiltApp.elon')),
            ],
        ),
    ]
