# Generated by Django 5.2 on 2025-05-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AltinGiltApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elon',
            name='moderation_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Moderator izohi (rad etish sababi)'),
        ),
        migrations.AddField(
            model_name='elon',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Moderatsiyada'), ('APPROVED', 'Tasdiqlangan'), ('REJECTED', 'Rad etilgan'), ('DRAFT', 'Qoralama')], db_index=True, default='PENDING', max_length=10),
        ),
    ]
