# Generated by Django 5.2.1 on 2025-05-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AltinGiltApp', '0002_shahar_tur_alter_elon_options_alter_rasm_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elon',
            name='manzil',
            field=models.CharField(blank=True, help_text="Ko'cha, uy raqami, mo'ljal (ixtiyoriy)", max_length=255, verbose_name='Aniq manzil'),
        ),
    ]
