"""
Django settings for AltinGilt project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+yfwfju^j5c+(y5(gym(s+0hfer%j3ebxr_^n@0)jpa22p-s&4'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    "https://1edb-84-54-71-19.ngrok-free.app",  # sizning ngrok domeningiz
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'AltinGiltApp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'AltinGilt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Loyiha darajasidagi templates papkasini qo'shing
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True, # Ilovalar ichidagi templates papkalarini ham qidirish (True qolishi kerak)
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth', # request.user ni shablonlarga avtomatik qo'shadi
                'django.contrib.messages.context_processors.messages', # messages ni shablonlarga avtomatik qo'shadi
                # 'django.template.context_processors.media', # Agar MEDIA_URL ni har bir shablonda kerak bo'lsa
            ],
        },
    },
]

WSGI_APPLICATION = 'AltinGilt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Media fayllar uchun sozlamalar (foydalanuvchi yuklagan fayllar)
MEDIA_URL = '/media/' # Brauzerda media fayllarga murojaat qilish uchun URL prefiksi
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # Fayllarni serverda saqlash uchun papka yo'li



LOGIN_URL = 'AltinGiltApp:login' # Bizning login view'imizning URL nomi
LOGIN_REDIRECT_URL = 'AltinGiltApp:bosh_sahifa' # Kirgandan keyin yo'naltiriladigan standart sahifa
LOGOUT_REDIRECT_URL = 'AltinGiltApp:bosh_sahifa' # Chiqqandan keyin yo'naltiriladigan standart sahifa